import type { ArenaSurvivorEnemyDefinition } from "./types.js";

export const arenaSurvivorEnemyDefinitions = [
  {
    id: "slime-blob",
    displayName: "Slime Blob",
    role: "chaser",
    tags: [
      "starter",
      "swarm",
      "basic",
    ],
    baseDescription: "Frueher Fodder-Gegner mit niedrigem Druck und sicherer Materialkurve.",
    minWave: 1,
    spawnWeight: 20,
    radius: 14,
    maxHp: 14,
    moveSpeed: 118,
    contactDamage: 8,
    contactDamageCooldownMs: 450,
    spritePath: "/arena-survivor/enemies/sprites/slime-blob.svg",
    portraitPath: "/arena-survivor/enemies/portraits/slime-blob.svg",
  },
  {
    id: "fang-crawler",
    displayName: "Fang Crawler",
    role: "chaser",
    tags: [
      "fast",
      "pressure",
      "hunter",
    ],
    baseDescription: "Schneller Chaser, der Kiting frueh testet.",
    minWave: 2,
    spawnWeight: 11,
    radius: 15,
    maxHp: 20,
    moveSpeed: 190,
    contactDamage: 10,
    contactDamageCooldownMs: 380,
    spritePath: "/arena-survivor/enemies/sprites/fang-crawler.svg",
    portraitPath: "/arena-survivor/enemies/portraits/fang-crawler.svg",
  },
  {
    id: "needle-runner",
    displayName: "Needle Runner",
    role: "chaser",
    tags: [
      "fast",
      "swarm",
      "flanker",
    ],
    baseDescription: "Sehr schneller, fragiler Druckgegner fuer fruehe Horden.",
    minWave: 3,
    spawnWeight: 8.5,
    radius: 11,
    maxHp: 16,
    moveSpeed: 220,
    contactDamage: 9,
    contactDamageCooldownMs: 340,
    spritePath: "/arena-survivor/enemies/sprites/fang-crawler.svg",
    portraitPath: "/arena-survivor/enemies/portraits/fang-crawler.svg",
  },
  {
    id: "stone-brute",
    displayName: "Stone Brute",
    role: "brute",
    tags: [
      "tank",
      "heavy",
      "slow",
    ],
    baseDescription: "Langsam, robust und mit hohem Kontaktschaden.",
    minWave: 6,
    spawnWeight: 5.5,
    radius: 22,
    maxHp: 95,
    moveSpeed: 98,
    contactDamage: 20,
    contactDamageCooldownMs: 560,
    spritePath: "/arena-survivor/enemies/sprites/stone-brute.svg",
    portraitPath: "/arena-survivor/enemies/portraits/stone-brute.svg",
  },
  {
    id: "shell-bulwark",
    displayName: "Shell Bulwark",
    role: "brute",
    tags: [
      "tank",
      "armor",
      "wall",
    ],
    baseDescription: "Mittlerer Blocker, der fruehe Builds zum Positionieren zwingt.",
    minWave: 9,
    spawnWeight: 4.4,
    radius: 19,
    maxHp: 150,
    moveSpeed: 112,
    contactDamage: 18,
    contactDamageCooldownMs: 520,
    spritePath: "/arena-survivor/enemies/sprites/stone-brute.svg",
    portraitPath: "/arena-survivor/enemies/portraits/stone-brute.svg",
  },
  {
    id: "ember-wisp",
    displayName: "Ember Wisp",
    role: "shooter",
    tags: [
      "ranged",
      "fire",
      "pressure",
    ],
    baseDescription: "Leichter Distanzgegner, der Feuerbolzen auf den Spieler schiesst.",
    minWave: 4,
    spawnWeight: 7,
    radius: 13,
    maxHp: 30,
    moveSpeed: 128,
    contactDamage: 12,
    contactDamageCooldownMs: 600,
    shootCooldownMs: 1650,
    shootRange: 310,
    projectile: {
      id: "ember-bolt",
      radius: 6,
      speed: 330,
      damage: 12,
      lifetimeMs: 2400,
      maxRange: 380,
      pierce: 1,
    },
    spritePath: "/arena-survivor/enemies/sprites/ember-wisp.svg",
    portraitPath: "/arena-survivor/enemies/portraits/ember-wisp.svg",
  },
  {
    id: "toxic-shroom",
    displayName: "Toxic Shroom",
    role: "shooter",
    tags: [
      "ranged",
      "poison",
      "area",
    ],
    baseDescription: "Gefaehrlicher Distanzgegner mit langsamen Giftsporen.",
    minWave: 8,
    spawnWeight: 5.8,
    radius: 16,
    maxHp: 56,
    moveSpeed: 98,
    contactDamage: 13,
    contactDamageCooldownMs: 650,
    shootCooldownMs: 2125,
    shootRange: 340,
    projectile: {
      id: "toxic-spore",
      radius: 7,
      speed: 275,
      damage: 10,
      lifetimeMs: 2600,
      maxRange: 420,
      pierce: 1,
    },
    spritePath: "/arena-survivor/enemies/sprites/toxic-shroom.svg",
    portraitPath: "/arena-survivor/enemies/portraits/toxic-shroom.svg",
  },
  {
    id: "ash-spitter",
    displayName: "Ash Spitter",
    role: "shooter",
    tags: [
      "ranged",
      "fire",
      "kiter",
    ],
    baseDescription: "Beweglicher Shooter, der ab mittleren Wellen Feuerlinien legt.",
    minWave: 11,
    spawnWeight: 4.8,
    radius: 14,
    maxHp: 72,
    moveSpeed: 146,
    contactDamage: 12,
    contactDamageCooldownMs: 560,
    shootCooldownMs: 1780,
    shootRange: 360,
    projectile: {
      id: "ember-bolt",
      radius: 5,
      speed: 390,
      damage: 11,
      lifetimeMs: 2300,
      maxRange: 460,
      pierce: 1,
    },
    spritePath: "/arena-survivor/enemies/sprites/ember-wisp.svg",
    portraitPath: "/arena-survivor/enemies/portraits/ember-wisp.svg",
  },
  {
    id: "plague-lobber",
    displayName: "Plague Lobber",
    role: "shooter",
    tags: [
      "ranged",
      "poison",
      "heavy",
    ],
    baseDescription: "Zaehere Distanzgefahr mit langsamen, schmerzhaften Giftkugeln.",
    minWave: 14,
    spawnWeight: 3.6,
    radius: 18,
    maxHp: 118,
    moveSpeed: 92,
    contactDamage: 15,
    contactDamageCooldownMs: 640,
    shootCooldownMs: 2450,
    shootRange: 410,
    projectile: {
      id: "toxic-spore",
      radius: 8,
      speed: 255,
      damage: 16,
      lifetimeMs: 2800,
      maxRange: 500,
      pierce: 1,
    },
    spritePath: "/arena-survivor/enemies/sprites/toxic-shroom.svg",
    portraitPath: "/arena-survivor/enemies/portraits/toxic-shroom.svg",
  },
  {
    id: "iron-mauler",
    displayName: "Iron Mauler",
    role: "brute",
    tags: [
      "elite",
      "tank",
      "heavy",
    ],
    baseDescription: "Spaeter Elite-Brute mit sehr viel Leben und klarer Nahkampfgefahr.",
    minWave: 16,
    spawnWeight: 2.4,
    radius: 28,
    maxHp: 360,
    moveSpeed: 88,
    contactDamage: 26,
    contactDamageCooldownMs: 500,
    spritePath: "/arena-survivor/enemies/sprites/stone-brute.svg",
    portraitPath: "/arena-survivor/enemies/portraits/stone-brute.svg",
  },
  {
    id: "loot-runner",
    displayName: "Loot Runner",
    role: "chaser",
    tags: [
      "loot",
      "fast",
      "bonus",
    ],
    baseDescription: "Schneller Bonusgegner mit wenig HP und hoher Drop-Wirkung ueber Luck.",
    minWave: 5,
    spawnWeight: 2.2,
    radius: 12,
    maxHp: 18,
    moveSpeed: 245,
    contactDamage: 8,
    contactDamageCooldownMs: 420,
    spritePath: "/arena-survivor/enemies/sprites/fang-crawler.svg",
    portraitPath: "/arena-survivor/enemies/portraits/fang-crawler.svg",
  },
  {
    id: "charger-hulk",
    displayName: "Charger Hulk",
    role: "brute",
    tags: [
      "charger",
      "elite",
      "pressure",
    ],
    baseDescription: "Schnellerer Bruiser fuer Midgame-Druckspitzen.",
    minWave: 12,
    spawnWeight: 3.2,
    radius: 23,
    maxHp: 185,
    moveSpeed: 145,
    contactDamage: 24,
    contactDamageCooldownMs: 460,
    spritePath: "/arena-survivor/enemies/sprites/stone-brute.svg",
    portraitPath: "/arena-survivor/enemies/portraits/stone-brute.svg",
  },
  {
    id: "elite-spitter",
    displayName: "Elite Spitter",
    role: "shooter",
    tags: [
      "ranged",
      "elite",
      "projectile",
    ],
    baseDescription: "Spaeter Elite-Shooter mit hohem Projektiltempo als Prioritaetsziel.",
    minWave: 17,
    spawnWeight: 2,
    radius: 18,
    maxHp: 145,
    moveSpeed: 118,
    contactDamage: 18,
    contactDamageCooldownMs: 600,
    shootCooldownMs: 1550,
    shootRange: 460,
    projectile: {
      id: "crimson-orb",
      radius: 7,
      speed: 440,
      damage: 18,
      lifetimeMs: 2600,
      maxRange: 540,
      pierce: 1,
    },
    spritePath: "/arena-survivor/enemies/sprites/ember-wisp.svg",
    portraitPath: "/arena-survivor/enemies/portraits/ember-wisp.svg",
  },
  {
    id: "scrap-goliath",
    displayName: "Scrap Goliath",
    role: "brute",
    tags: [
      "boss",
      "mini-boss",
      "heavy",
      "metal",
    ],
    baseDescription: "Ein massiver Mini-Boss, der einmalig in Welle 10 auf das Team losgeht.",
    minWave: 10,
    spawnWeight: 0,
    radius: 45,
    maxHp: 1150,
    moveSpeed: 92,
    contactDamage: 28,
    contactDamageCooldownMs: 430,
    spritePath: "/arena-survivor/enemies/sprites/scrap-goliath.svg",
    portraitPath: "/arena-survivor/enemies/portraits/scrap-goliath.svg",
  },
  {
    id: "crimson-overlord",
    displayName: "Crimson Overlord",
    role: "shooter",
    tags: [
      "boss",
      "ranged",
      "radial",
      "crimson",
    ],
    baseDescription: "Der Welle-20-Boss entfesselt alle 5 Sekunden einen Ring aus roten Kugeln.",
    minWave: 20,
    spawnWeight: 0,
    radius: 60,
    maxHp: 4200,
    moveSpeed: 74,
    contactDamage: 34,
    contactDamageCooldownMs: 520,
    shootCooldownMs: 5000,
    shootRange: 460,
    projectile: {
      id: "crimson-orb",
      radius: 10,
      speed: 280,
      damage: 18,
      lifetimeMs: 3200,
      maxRange: 640,
      pierce: 1,
    },
    spritePath: "/arena-survivor/enemies/sprites/crimson-overlord.svg",
    portraitPath: "/arena-survivor/enemies/portraits/crimson-overlord.svg",
  },
] as const satisfies readonly ArenaSurvivorEnemyDefinition[];

export const arenaSurvivorEnemyDefinitionsById = Object.fromEntries(
  arenaSurvivorEnemyDefinitions.map((enemy) => [enemy.id, enemy])
) satisfies Record<string, ArenaSurvivorEnemyDefinition>;
