import type { ArenaSurvivorWeaponDefinition } from "./types.js";

export const arenaSurvivorWeaponDefinitions = [
  {
    id: "rust-blade",
    name: "Rostklinge",
    category: "melee",
    tags: [
      "melee",
      "physical",
      "starter",
      "balanced",
    ],
    baseDescription: "Ausgewogene Nahkampfwaffe mit solider Reichweite und zuverlaessiger DPS.",
    levels: [
      {
        level: 1,
        cost: 8,
        damage: 18,
        cooldownMs: 650,
        range: 84,
        projectileSpeed: 0,
        knockback: 0.1,
        description: "Solider Grundschlag ohne klare Schwache.",
      },
      {
        level: 2,
        cost: 12,
        damage: 23,
        cooldownMs: 620,
        range: 89,
        projectileSpeed: 0,
        knockback: 0.12,
        description: "Etwas mehr Schaden und minimal flotter.",
      },
      {
        level: 3,
        cost: 16,
        damage: 29,
        cooldownMs: 585,
        range: 94,
        projectileSpeed: 0,
        knockback: 0.15,
        critScale: 1.05,
        description: "Spuerbar staerker und angenehmer im Nahkampf.",
      },
      {
        level: 4,
        cost: 21,
        damage: 36,
        cooldownMs: 545,
        range: 98,
        projectileSpeed: 0,
        knockback: 0.18,
        critScale: 1.05,
        description: "Stabiler Endgame-Allrounder fuer physische Melee-Builds.",
      },
    ],
  },
  {
    id: "twin-daggers",
    name: "Doppeldolche",
    category: "melee",
    tags: [
      "melee",
      "physical",
      "precise",
      "crit",
    ],
    baseDescription: "Sehr schnelle Nahkampfwaffe. Perfekt fuer Lifesteal-, Crit- und On-Hit-Synergien.",
    levels: [
      {
        level: 1,
        cost: 10,
        damage: 6,
        cooldownMs: 404,
        range: 68,
        projectileSpeed: 0,
        critChancePct: 20,
        critScale: 2.5,
        damageScaling: { meleePower: 0.8 },
        knockback: 0.05,
        description: "Lv. 1: niedriger Schaden, aber hohe Crit-Chance.",
      },
      {
        level: 2,
        cost: 14,
        damage: 9,
        cooldownMs: 372,
        range: 68,
        projectileSpeed: 0,
        critChancePct: 30,
        critScale: 3,
        damageScaling: { meleePower: 0.8 },
        knockback: 0.06,
        description: "Lv. 2: Crit-Builds skalieren deutlich besser.",
      },
      {
        level: 3,
        cost: 18,
        damage: 12,
        cooldownMs: 344,
        range: 68,
        projectileSpeed: 0,
        critChancePct: 40,
        critScale: 3.5,
        damageScaling: { meleePower: 0.8 },
        knockback: 0.07,
        description: "Lv. 3: 40% Basis-Crit mit hoher Crit-Wucht.",
      },
      {
        level: 4,
        cost: 24,
        damage: 20,
        cooldownMs: 312,
        range: 68,
        projectileSpeed: 0,
        critChancePct: 50,
        critScale: 4,
        damageScaling: { meleePower: 0.8 },
        knockback: 0.08,
        description: "Lv. 4: sehr hoher Single-Target-Crit-Burst.",
      },
    ],
  },
  {
    id: "war-hammer",
    name: "Kriegshammer",
    category: "melee",
    tags: [
      "melee",
      "physical",
      "heavy",
      "burst",
    ],
    baseDescription: "Langsame, harte Nahkampfwaffe fuer tankige Burst-Builds.",
    levels: [
      {
        level: 1,
        cost: 12,
        damage: 34,
        cooldownMs: 1100,
        range: 96,
        projectileSpeed: 0,
        knockback: 0.26,
        description: "Sehr hoher Treffer, aber traege.",
      },
      {
        level: 2,
        cost: 17,
        damage: 42,
        cooldownMs: 1040,
        range: 101,
        projectileSpeed: 0,
        knockback: 0.29,
        description: "Spuerbarer Powersprung mit etwas besserem Flow.",
      },
      {
        level: 3,
        cost: 23,
        damage: 52,
        cooldownMs: 970,
        range: 106,
        projectileSpeed: 0,
        knockback: 0.32,
        critScale: 1.1,
        description: "Massiver Schaden gegen einzelne Ziele.",
      },
      {
        level: 4,
        cost: 30,
        damage: 64,
        cooldownMs: 900,
        range: 110,
        projectileSpeed: 0,
        knockback: 0.36,
        pierce: 1,
        critScale: 1.15,
        description: "Brutaler Heavy-Hitter fuer Tank- und Burst-Archetypen.",
      },
    ],
  },
  {
    id: "spear",
    name: "Speer",
    category: "melee",
    tags: [
      "melee",
      "physical",
      "primitive",
      "reach",
      "starter",
    ],
    baseDescription: "Lange Nahkampfwaffe mit 100% Melee-Skalierung und niedriger Basis-Crit-Chance.",
    levels: [
      {
        level: 1,
        cost: 9,
        damage: 15,
        cooldownMs: 610,
        range: 130,
        projectileSpeed: 0,
        critChancePct: 3,
        critScale: 2,
        damageScaling: { meleePower: 1 },
        knockback: 0,
        description: "Lv. 1: langer Stoss mit 15 Schaden und voller Melee-Skalierung.",
      },
      {
        level: 2,
        cost: 13,
        damage: 25,
        cooldownMs: 560,
        range: 140,
        projectileSpeed: 0,
        critChancePct: 3,
        critScale: 2,
        damageScaling: { meleePower: 1 },
        knockback: 0,
        description: "Lv. 2: 25 Schaden und etwas sicherere Reichweite.",
      },
      {
        level: 3,
        cost: 18,
        damage: 40,
        cooldownMs: 512,
        range: 150,
        projectileSpeed: 0,
        critChancePct: 3,
        critScale: 2,
        damageScaling: { meleePower: 1 },
        knockback: 0,
        description: "Lv. 3: starker Midgame-Stich mit 40 Schaden.",
      },
      {
        level: 4,
        cost: 24,
        damage: 60,
        cooldownMs: 496,
        range: 185,
        projectileSpeed: 0,
        critChancePct: 3,
        critScale: 2,
        damageScaling: { meleePower: 1 },
        knockback: 0,
        description: "Lv. 4: 60 Schaden und sehr hohe Reichweite.",
      },
    ],
  },
  {
    id: "lance",
    name: "Lanze",
    category: "melee",
    tags: [
      "melee",
      "physical",
      "reach",
      "heavy",
    ],
    baseDescription: "Noch laenger als der Speer, dafuer etwas schwerfaelliger. Stark gegen einzelne Ziele.",
    levels: [
      {
        level: 1,
        cost: 12,
        damage: 28,
        cooldownMs: 760,
        range: 130,
        projectileSpeed: 0,
        knockback: 0.18,
        description: "Langer, harter Stoß mit viel Sicherheit.",
      },
      {
        level: 2,
        cost: 17,
        damage: 34,
        cooldownMs: 718,
        range: 137,
        projectileSpeed: 0,
        knockback: 0.2,
        description: "Mehr Durchschlagskraft bei weiterhin hohem Reach.",
      },
      {
        level: 3,
        cost: 23,
        damage: 41,
        cooldownMs: 675,
        range: 144,
        projectileSpeed: 0,
        knockback: 0.22,
        critScale: 1.08,
        description: "Spuerbar staerker gegen dickere Ziele.",
      },
      {
        level: 4,
        cost: 31,
        damage: 50,
        cooldownMs: 632,
        range: 151,
        projectileSpeed: 0,
        knockback: 0.24,
        pierce: 1,
        critScale: 1.1,
        description: "Durchbohrt Frontlinien und bleibt dabei sehr sicher.",
      },
    ],
  },
  {
    id: "stone",
    name: "Stein",
    category: "melee",
    tags: [
      "melee",
      "physical",
      "primitive",
      "blunt",
      "armor",
    ],
    baseDescription: "Unverfeinert, aber effektiv. Ein dicker Stein fuer kurze, harte Treffer.",
    levels: [
      {
        level: 1,
        cost: 7,
        damage: 20,
        cooldownMs: 672,
        range: 70,
        projectileSpeed: 0,
        critChancePct: 10,
        critScale: 1.5,
        damageScaling: { meleePower: 1 },
        knockback: 0.12,
        description: "Lv. 1: kurze Reichweite, hoher Crit und schwerer Treffer.",
      },
      {
        level: 2,
        cost: 11,
        damage: 35,
        cooldownMs: 644,
        range: 70,
        projectileSpeed: 0,
        critChancePct: 15,
        critScale: 1.5,
        damageScaling: { meleePower: 1 },
        knockback: 0.12,
        description: "Lv. 2: massiver Schadenssprung mit 15% Basis-Crit.",
      },
      {
        level: 3,
        cost: 15,
        damage: 50,
        cooldownMs: 612,
        range: 70,
        projectileSpeed: 0,
        critChancePct: 20,
        critScale: 1.5,
        damageScaling: { meleePower: 1 },
        knockback: 0.12,
        description: "Lv. 3: 50 Schaden mit hoher Crit-Wahrscheinlichkeit.",
      },
      {
        level: 4,
        cost: 21,
        damage: 70,
        cooldownMs: 584,
        range: 70,
        projectileSpeed: 0,
        critChancePct: 25,
        critScale: 1.5,
        damageScaling: { meleePower: 1 },
        knockback: 0.12,
        description: "Lv. 4: schwerer Tank-Hit mit 70 Schaden.",
      },
    ],
  },
  {
    id: "stick",
    name: "Stock",
    category: "melee",
    tags: [
      "melee",
      "physical",
      "primitive",
      "swarm",
    ],
    baseDescription: "Schnelle, leichte Nahkampfwaffe mit wenig Schaden pro Treffer, aber gutem Flow.",
    levels: [
      {
        level: 1,
        cost: 6,
        damage: 8,
        cooldownMs: 516,
        range: 76,
        projectileSpeed: 0,
        critChancePct: 3,
        critScale: 1.5,
        damageScaling: { meleePower: 1 },
        knockback: 0.05,
        description: "Lv. 1: niedriger Basisschaden, gute Skalierung.",
      },
      {
        level: 2,
        cost: 10,
        damage: 9,
        cooldownMs: 488,
        range: 76,
        projectileSpeed: 0,
        critChancePct: 3,
        critScale: 1.5,
        damageScaling: { meleePower: 1 },
        knockback: 0.06,
        description: "Lv. 2: kaum mehr Base, dafuer bessere Feuerfolge.",
      },
      {
        level: 3,
        cost: 14,
        damage: 10,
        cooldownMs: 460,
        range: 76,
        projectileSpeed: 0,
        knockback: 0.07,
        critChancePct: 3,
        critScale: 1.5,
        damageScaling: { meleePower: 1 },
        description: "Lv. 3: bleibt build-abhaengig und skaliert ueber Melee.",
      },
      {
        level: 4,
        cost: 20,
        damage: 12,
        cooldownMs: 436,
        range: 76,
        projectileSpeed: 0,
        knockback: 0.08,
        critChancePct: 3,
        critScale: 1.5,
        damageScaling: { meleePower: 1 },
        description: "Lv. 4: guenstige DPS-Basis fuer Kopie-Builds.",
      },
    ],
  },
  {
    id: "pitchfork",
    name: "Mistgabel",
    category: "melee",
    tags: [
      "melee",
      "physical",
      "reach",
      "cleave",
    ],
    baseDescription: "Lange Bauernwaffe, die mehrere Gegner in der Frontlinie gleichzeitig erwischt.",
    levels: [
      {
        level: 1,
        cost: 10,
        damage: 18,
        cooldownMs: 610,
        range: 106,
        projectileSpeed: 0,
        knockback: 0.11,
        pierce: 1,
        description: "Erreicht mehrere Ziele in einer Linie.",
      },
      {
        level: 2,
        cost: 15,
        damage: 23,
        cooldownMs: 580,
        range: 113,
        projectileSpeed: 0,
        knockback: 0.13,
        pierce: 1,
        description: "Mehr Schaden bei gleich gutem Frontline-Druck.",
      },
      {
        level: 3,
        cost: 20,
        damage: 29,
        cooldownMs: 548,
        range: 120,
        projectileSpeed: 0,
        knockback: 0.15,
        pierce: 2,
        description: "Schiebt sich sehr angenehm durch kleine Gruppen.",
      },
      {
        level: 4,
        cost: 27,
        damage: 36,
        cooldownMs: 516,
        range: 127,
        projectileSpeed: 0,
        knockback: 0.17,
        pierce: 2,
        critScale: 1.06,
        description: "Stabile Gruppenwaffe fuer volle Nahkampf-Builds.",
      },
    ],
  },
  {
    id: "halberd",
    name: "Hellebarde",
    category: "melee",
    tags: [
      "melee",
      "physical",
      "heavy",
      "reach",
    ],
    baseDescription: "Wuchtige Stangenwaffe mit guter Reichweite und starkem Einzelzielschaden.",
    levels: [
      {
        level: 1,
        cost: 13,
        damage: 30,
        cooldownMs: 840,
        range: 122,
        projectileSpeed: 0,
        knockback: 0.2,
        description: "Schwerer Treffer mit langem Reach.",
      },
      {
        level: 2,
        cost: 18,
        damage: 37,
        cooldownMs: 795,
        range: 130,
        projectileSpeed: 0,
        knockback: 0.23,
        description: "Fuehlt sich merklich schwerer und haerter an.",
      },
      {
        level: 3,
        cost: 25,
        damage: 45,
        cooldownMs: 748,
        range: 137,
        projectileSpeed: 0,
        knockback: 0.26,
        critScale: 1.1,
        description: "Starke Burst-Waffe fuer schwere Melee-Builds.",
      },
      {
        level: 4,
        cost: 33,
        damage: 54,
        cooldownMs: 702,
        range: 144,
        projectileSpeed: 0,
        knockback: 0.29,
        pierce: 1,
        critScale: 1.14,
        description: "Hoher Endgame-Druck mit spuerbarem Frontline-Reach.",
      },
    ],
  },
  {
    id: "mace",
    name: "Morgenstern",
    category: "melee",
    tags: [
      "melee",
      "physical",
      "heavy",
      "stun",
    ],
    baseDescription: "Langsamer, massiver Schaedelschalter fuer pure Wucht und hohen Knockback.",
    levels: [
      {
        level: 1,
        cost: 11,
        damage: 32,
        cooldownMs: 980,
        range: 84,
        projectileSpeed: 0,
        knockback: 0.24,
        description: "Kurzer, brutaler Einschlag.",
      },
      {
        level: 2,
        cost: 16,
        damage: 39,
        cooldownMs: 934,
        range: 89,
        projectileSpeed: 0,
        knockback: 0.27,
        description: "Noch mehr Masse hinter jedem Treffer.",
      },
      {
        level: 3,
        cost: 22,
        damage: 48,
        cooldownMs: 886,
        range: 94,
        projectileSpeed: 0,
        knockback: 0.3,
        critScale: 1.08,
        description: "Guter Bruiser-Hit fuer dickere Gegner.",
      },
      {
        level: 4,
        cost: 29,
        damage: 58,
        cooldownMs: 836,
        range: 98,
        projectileSpeed: 0,
        knockback: 0.34,
        critScale: 1.12,
        description: "Extrem wuchtige Endgame-Keule mit starkem Impact.",
      },
    ],
  },
  {
    id: "cleaver",
    name: "Hackbeil",
    category: "melee",
    tags: [
      "melee",
      "physical",
      "blade",
      "health",
    ],
    baseDescription: "Kurze Klinge mit Max-HP-Skalierung fuer tankige Nahkampf-Builds.",
    levels: [
      {
        level: 1,
        cost: 9,
        damage: 6,
        cooldownMs: 396,
        range: 66,
        projectileSpeed: 0,
        critChancePct: 10,
        damageScaling: { meleePower: 0.5, maxHp: 0.15 },
        knockback: 0.09,
        critScale: 2,
        description: "Lv. 1: kleiner Hit mit Max-HP-Skalierung.",
      },
      {
        level: 2,
        cost: 13,
        damage: 12,
        cooldownMs: 396,
        range: 72,
        projectileSpeed: 0,
        critChancePct: 15,
        damageScaling: { meleePower: 0.5, maxHp: 0.2 },
        knockback: 0.1,
        critScale: 2,
        description: "Lv. 2: 20% Max-HP-Skalierung.",
      },
      {
        level: 3,
        cost: 18,
        damage: 18,
        cooldownMs: 384,
        range: 80,
        projectileSpeed: 0,
        critChancePct: 20,
        damageScaling: { meleePower: 0.5, maxHp: 0.25 },
        knockback: 0.11,
        critScale: 2,
        description: "Lv. 3: HP-Tank wird zur Offense.",
      },
      {
        level: 4,
        cost: 24,
        damage: 30,
        cooldownMs: 356,
        range: 86,
        projectileSpeed: 0,
        critChancePct: 25,
        damageScaling: { meleePower: 0.5, maxHp: 0.3 },
        knockback: 0.12,
        critScale: 2,
        description: "Lv. 4: starker Hit plus hohe Max-HP-Skalierung.",
      },
    ],
  },
  {
    id: "survivor-pistol",
    name: "Ueberlebenspistole",
    category: "ranged",
    projectileDefinitionId: "pistol-round",
    tags: [
      "ranged",
      "physical",
      "gun",
      "starter",
      "pierce",
    ],
    baseDescription: "Ausgewogene Fernkampfwaffe mit verlaesslichem Tempo und guter Reichweite.",
    levels: [
      {
        level: 1,
        cost: 9,
        damage: 12,
        cooldownMs: 480,
        range: 360,
        projectileSpeed: 760,
        pierce: 1,
        critChancePct: 5,
        critScale: 2,
        damageScaling: { rangedPower: 1 },
        knockback: 0.08,
        description: "Lv. 1: solider Schuss mit 100% Fernkampf-Skalierung.",
      },
      {
        level: 2,
        cost: 13,
        damage: 20,
        cooldownMs: 448,
        range: 360,
        projectileSpeed: 790,
        pierce: 1,
        critChancePct: 10,
        critScale: 2,
        damageScaling: { rangedPower: 1 },
        knockback: 0.08,
        description: "Lv. 2: 20 Schaden und 10% Basis-Crit.",
      },
      {
        level: 3,
        cost: 18,
        damage: 30,
        cooldownMs: 412,
        range: 360,
        projectileSpeed: 820,
        pierce: 1,
        critChancePct: 15,
        critScale: 2,
        damageScaling: { rangedPower: 1 },
        knockback: 0.08,
        description: "Lv. 3: verlaesslicher Midgame-Pick.",
      },
      {
        level: 4,
        cost: 24,
        damage: 50,
        cooldownMs: 348,
        range: 360,
        projectileSpeed: 860,
        pierce: 1,
        critChancePct: 20,
        critScale: 2,
        damageScaling: { rangedPower: 1 },
        knockback: 0.08,
        description: "Lv. 4: hoher Fernkampf-Burst mit 20% Basis-Crit.",
      },
    ],
  },
  {
    id: "hunter-bow",
    name: "Jagdbogen",
    category: "ranged",
    projectileDefinitionId: "hunter-arrow",
    tags: [
      "ranged",
      "physical",
      "burst",
      "crit",
    ],
    baseDescription: "Langsamer, praeziser Fernkampf mit starken Einzelprojektilen.",
    levels: [
      {
        level: 1,
        cost: 11,
        damage: 28,
        cooldownMs: 950,
        range: 520,
        projectileSpeed: 760,
        critScale: 1.1,
        description: "Hoher Einzelschaden, aber gemachliches Tempo.",
      },
      {
        level: 2,
        cost: 16,
        damage: 35,
        cooldownMs: 900,
        range: 545,
        projectileSpeed: 800,
        critScale: 1.14,
        description: "Noch haertere Treffer und bessere Projektilfuehrung.",
      },
      {
        level: 3,
        cost: 25,
        damage: 39,
        cooldownMs: 845,
        range: 570,
        projectileSpeed: 840,
        critScale: 1.18,
        description: "Stark in Crit- und Ranged-Power-Builds.",
      },
      {
        level: 4,
        cost: 32,
        damage: 46,
        cooldownMs: 838,
        range: 600,
        projectileSpeed: 885,
        pierce: 1,
        critScale: 1.24,
        description: "Elite-Bogen fuer praezise Glaskanonen-Builds.",
      },
    ],
  },
  {
    id: "scrap-smg",
    name: "Schrottsalve",
    category: "ranged",
    projectileDefinitionId: "smg-pellet",
    tags: [
      "ranged",
      "physical",
      "fast",
      "projectile",
    ],
    baseDescription: "Viele kleine Treffer. Stark mit Angriffstempo, Projektilen und Lifesteal.",
    levels: [
      {
        level: 1,
        cost: 12,
        damage: 3,
        cooldownMs: 140,
        range: 360,
        projectileSpeed: 780,
        critChancePct: 1,
        critScale: 1.5,
        damageScaling: { rangedPower: 0.5 },
        description: "Lv. 1: sehr schnelle Feuerfolge mit geringem Einzelschaden.",
      },
      {
        level: 2,
        cost: 17,
        damage: 4,
        cooldownMs: 136,
        range: 360,
        projectileSpeed: 800,
        critChancePct: 1,
        critScale: 1.5,
        damageScaling: { rangedPower: 0.6 },
        description: "Lv. 2: niedrige Base, bessere Fernkampf-Skalierung.",
      },
      {
        level: 3,
        cost: 23,
        damage: 5,
        cooldownMs: 132,
        range: 360,
        projectileSpeed: 820,
        critChancePct: 1,
        critScale: 1.5,
        damageScaling: { rangedPower: 0.7 },
        description: "Lv. 3: On-Hit- und Lifesteal-Traeger.",
      },
      {
        level: 4,
        cost: 40,
        damage: 8,
        cooldownMs: 120,
        range: 360,
        projectileSpeed: 840,
        critChancePct: 1,
        critScale: 1.5,
        damageScaling: { rangedPower: 0.8 },
        description: "Lv. 4: sehr schnelles Dauerfeuer mit starker Fernkampf-Skalierung.",
      },
    ],
  },
  {
    id: "ember-wand",
    name: "Glutstab",
    category: "magic",
    projectileDefinitionId: "ember-orb",
    tags: [
      "magic",
      "elemental",
      "fire",
      "balanced",
    ],
    baseDescription: "Ausgewogene Feuer-Magiewaffe mit guter Skalierung ueber Magic- und Elementarwerte.",
    levels: [
      {
        level: 1,
        cost: 11,
        damage: 4,
        cooldownMs: 348,
        range: 330,
        projectileSpeed: 620,
        critChancePct: 0,
        critScale: 2,
        damageScaling: { magicPower: 0.5, elementalPower: 0.5 },
        description: "Lv. 1: schwacher Hit, skaliert ueber Magie und Elementar.",
      },
      {
        level: 2,
        cost: 16,
        damage: 6,
        cooldownMs: 312,
        range: 350,
        projectileSpeed: 650,
        critChancePct: 0,
        critScale: 2,
        damageScaling: { magicPower: 0.65, elementalPower: 0.65 },
        description: "Lv. 2: bessere Skalierung statt hoher Base.",
      },
      {
        level: 3,
        cost: 22,
        damage: 8,
        cooldownMs: 280,
        range: 370,
        projectileSpeed: 680,
        critChancePct: 0,
        critScale: 2,
        damageScaling: { magicPower: 0.8, elementalPower: 0.8 },
        description: "Lv. 3: schneller Elementar-Traeger.",
      },
      {
        level: 4,
        cost: 29,
        damage: 12,
        cooldownMs: 212,
        range: 390,
        projectileSpeed: 720,
        critChancePct: 0,
        critScale: 2,
        damageScaling: { magicPower: 1, elementalPower: 1 },
        description: "Lv. 4: sehr schneller Stab mit voller Elementar-Skalierung.",
      },
    ],
  },
  {
    id: "frost-orb",
    name: "Frostorb",
    category: "magic",
    projectileDefinitionId: "frost-shard",
    tags: [
      "magic",
      "elemental",
      "ice",
      "control",
    ],
    baseDescription: "Defensiv gepraegte Magiewaffe mit kontrolliertem, sicherem Schadensprofil.",
    levels: [
      {
        level: 1,
        cost: 10,
        damage: 18,
        cooldownMs: 850,
        range: 380,
        projectileSpeed: 450,
        description: "Sicherer, ruhiger Magie-Angriff mit ordentlicher Reichweite.",
      },
      {
        level: 2,
        cost: 15,
        damage: 23,
        cooldownMs: 800,
        range: 395,
        projectileSpeed: 480,
        description: "Etwas oefter und praeziser einsetzbar.",
      },
      {
        level: 3,
        cost: 20,
        damage: 29,
        cooldownMs: 745,
        range: 410,
        projectileSpeed: 520,
        description: "Ausgeglichen zwischen Kontrolle und DPS.",
      },
      {
        level: 4,
        cost: 27,
        damage: 35,
        cooldownMs: 690,
        range: 430,
        projectileSpeed: 560,
        pierce: 1,
        description: "Sehr stark fuer defensive Kite-Builds.",
      },
    ],
  },
  {
    id: "spark-rod",
    name: "Blitzfunke",
    category: "magic",
    projectileDefinitionId: "spark-bolt",
    tags: [
      "magic",
      "elemental",
      "lightning",
      "fast",
    ],
    baseDescription: "Sehr schnelle Magiewaffe mit starker Synergie zu Angriffstempo und Crit.",
    levels: [
      {
        level: 1,
        cost: 12,
        damage: 11,
        cooldownMs: 260,
        range: 360,
        projectileSpeed: 900,
        description: "Schneller Magie-Tick mit geringerem Einzelschaden.",
      },
      {
        level: 2,
        cost: 17,
        damage: 14,
        cooldownMs: 240,
        range: 370,
        projectileSpeed: 940,
        critScale: 1.04,
        description: "Noch fluessiger und leicht staerker.",
      },
      {
        level: 3,
        cost: 23,
        damage: 18,
        cooldownMs: 218,
        range: 382,
        projectileSpeed: 980,
        critScale: 1.08,
        description: "Exzellent fuer Speed- und Elementar-Builds.",
      },
      {
        level: 4,
        cost: 40,
        damage: 17,
        cooldownMs: 196,
        range: 395,
        projectileSpeed: 1030,
        projectileCount: 2,
        critScale: 1.12,
        description: "Aggressive Endgame-Magiewaffe mit hohem Tempo.",
      },
    ],
  },
  {
    id: "coil-rifle",
    name: "Spulenkarabiner",
    category: "ranged",
    projectileDefinitionId: "coil-spike",
    tags: [
      "ranged",
      "physical",
      "precision",
      "pierce",
    ],
    baseDescription: "Praeziser Magnetschuss mit hoher Projektilgeschwindigkeit und sauberer Durchschlags-Skalierung.",
    levels: [
      {
        level: 1,
        cost: 11,
        damage: 21,
        cooldownMs: 620,
        range: 500,
        projectileSpeed: 860,
        description: "Schneller Praezisionsschuss mit solider Reichweite.",
      },
      {
        level: 2,
        cost: 16,
        damage: 27,
        cooldownMs: 585,
        range: 520,
        projectileSpeed: 900,
        critScale: 1.05,
        description: "Fluessiger und deutlich haerter im Treffer.",
      },
      {
        level: 3,
        cost: 22,
        damage: 34,
        cooldownMs: 545,
        range: 545,
        projectileSpeed: 945,
        pierce: 1,
        critScale: 1.08,
        description: "Durchschlaegt Linien besser und bleibt sehr praezise.",
      },
      {
        level: 4,
        cost: 30,
        damage: 42,
        cooldownMs: 505,
        range: 575,
        projectileSpeed: 990,
        pierce: 1,
        critScale: 1.12,
        description: "Endgame-Karabiner fuer stabile Single-Target- und Pierce-Builds.",
      },
    ],
  },
  {
    id: "gear-launcher",
    name: "Zahnradwerfer",
    category: "ranged",
    projectileDefinitionId: "gear-shot",
    tags: [
      "ranged",
      "physical",
      "projectile",
      "burst",
    ],
    baseDescription: "Verschiesst streuende Schrottzahnraeder. Stark mit Projektilen, aber nur auf kurze bis mittlere Distanz.",
    levels: [
      {
        level: 1,
        cost: 12,
        damage: 9,
        cooldownMs: 520,
        range: 300,
        projectileSpeed: 620,
        projectileCount: 2,
        description: "Breiter Schrotschuss fuer Naehe und Seitentreffer.",
      },
      {
        level: 2,
        cost: 17,
        damage: 11,
        cooldownMs: 485,
        range: 315,
        projectileSpeed: 650,
        projectileCount: 2,
        description: "Dichterer Schrottregen mit besserem Druck.",
      },
      {
        level: 3,
        cost: 24,
        damage: 12,
        cooldownMs: 450,
        range: 330,
        projectileSpeed: 680,
        projectileCount: 3,
        description: "Sehr stark mit Projektil- und Burst-Synergien.",
      },
      {
        level: 4,
        cost: 33,
        damage: 14,
        cooldownMs: 420,
        range: 345,
        projectileSpeed: 710,
        projectileCount: 3,
        pierce: 1,
        description: "Aggressiver Endgame-Werfer fuer kurze Reichweite.",
      },
    ],
  },
  {
    id: "venom-siphon",
    name: "Giftsiphon",
    category: "magic",
    projectileDefinitionId: "venom-dart",
    tags: [
      "magic",
      "elemental",
      "poison",
      "fast",
    ],
    baseDescription: "Verspritzt giftige Nadeln in schneller Folge. Ideal fuer Tempo-, Sustain- und aggressive Kite-Builds.",
    levels: [
      {
        level: 1,
        cost: 11,
        damage: 12,
        cooldownMs: 300,
        range: 350,
        projectileSpeed: 540,
        description: "Schneller Giftschuss mit eher kurzer Reichweite.",
      },
      {
        level: 2,
        cost: 16,
        damage: 15,
        cooldownMs: 278,
        range: 362,
        projectileSpeed: 575,
        description: "Mehr Druck und etwas bessere Fuehrung.",
      },
      {
        level: 3,
        cost: 22,
        damage: 19,
        cooldownMs: 254,
        range: 376,
        projectileSpeed: 610,
        description: "Sehr konstante Magie-DPS fuer schnelle Builds.",
      },
      {
        level: 4,
        cost: 31,
        damage: 24,
        cooldownMs: 228,
        range: 392,
        projectileSpeed: 650,
        pierce: 1,
        description: "Dichter Endgame-Druck fuer aggressive Elementar-Setups.",
      },
    ],
  },
  {
    id: "prism-scepter",
    name: "Prismenzepter",
    category: "magic",
    projectileDefinitionId: "prism-shard",
    tags: [
      "magic",
      "elemental",
      "arcane",
      "crit",
    ],
    baseDescription: "Buendelt schillernde Splitter zu schweren Arkan-Schuesse. Weniger Tempo, dafuer starke Crit-Skalierung.",
    levels: [
      {
        level: 1,
        cost: 12,
        damage: 24,
        cooldownMs: 760,
        range: 450,
        projectileSpeed: 690,
        critScale: 1.1,
        description: "Sauberer Arkan-Schuss mit gutem Burst.",
      },
      {
        level: 2,
        cost: 18,
        damage: 30,
        cooldownMs: 715,
        range: 470,
        projectileSpeed: 725,
        critScale: 1.14,
        description: "Mehr Wucht und besseres Projektiltempo.",
      },
      {
        level: 3,
        cost: 25,
        damage: 37,
        cooldownMs: 665,
        range: 490,
        projectileSpeed: 760,
        critScale: 1.18,
        description: "Sehr stark in Crit- und Magic-Builds.",
      },
      {
        level: 4,
        cost: 34,
        damage: 45,
        cooldownMs: 620,
        range: 515,
        projectileSpeed: 800,
        pierce: 1,
        critScale: 1.24,
        description: "Schwerer Endgame-Caster fuer Arcane-Crit-Builds.",
      },
    ],
  },
] as const satisfies readonly ArenaSurvivorWeaponDefinition[];

export const arenaSurvivorWeaponDefinitionsById = Object.fromEntries(
  arenaSurvivorWeaponDefinitions.map((weapon) => [weapon.id, weapon])
) satisfies Record<string, ArenaSurvivorWeaponDefinition>;

export const arenaSurvivorStarterWeaponDefinition =
  arenaSurvivorWeaponDefinitions.find((weapon) => weapon.id === "rust-blade") ??
  arenaSurvivorWeaponDefinitions[0];
